# Generated by Django 5.0.4 on 2024-04-26 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_Application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datas',
            name='Age',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='datas',
            name='Contact',
            field=models.IntegerField(default=''),
        ),
    ]
