# Generated by Django 5.0.4 on 2024-04-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_Application', '0002_alter_datas_age_alter_datas_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=20)),
                ('Roll_no', models.IntegerField(default='')),
                ('Email', models.CharField(default='', max_length=50)),
                ('Event_name', models.CharField(default='', max_length=255)),
                ('Event_cordinator', models.CharField(default='', max_length=100)),
                ('Event_date', models.DateField(default='')),
            ],
        ),
        migrations.DeleteModel(
            name='Datas',
        ),
    ]
