# Generated by Django 5.0.4 on 2024-04-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_Application', '0003_eventdata_delete_datas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdata',
            name='Roll_no',
            field=models.CharField(default='', max_length=50),
        ),
    ]
