# Generated by Django 5.0.4 on 2024-04-30 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_Application', '0004_alter_eventdata_roll_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdata',
            name='Name',
            field=models.CharField(default='', max_length=25),
        ),
    ]
