# Generated by Django 5.0.4 on 2024-04-30 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_Application', '0005_alter_eventdata_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Latitude', models.FloatField(default='', max_length=20)),
                ('Longitude', models.FloatField(default='', max_length=20)),
                ('Time', models.TimeField(default='')),
                ('Date', models.DateField(default='')),
                ('Image', models.ImageField(default='', upload_to='')),
            ],
        ),
    ]
