# Generated by Django 5.0.4 on 2024-04-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_Application', '0006_locationdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationdata',
            name='Date',
            field=models.CharField(default='', max_length=20),
        ),
    ]
