# Generated by Django 5.0.4 on 2024-04-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_Application', '0008_alter_locationdata_date_alter_locationdata_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationdata',
            name='Date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='locationdata',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='geotag_photos/'),
        ),
        migrations.AlterField(
            model_name='locationdata',
            name='Latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='locationdata',
            name='Longitude',
            field=models.FloatField(default=0),
        ),
    ]
