# Generated by Django 5.0.4 on 2024-04-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_Application', '0009_alter_locationdata_date_alter_locationdata_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationdata',
            name='Image',
            field=models.FileField(upload_to=''),
        ),
    ]
