# Generated by Django 5.0.4 on 2024-05-02 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_Application', '0010_alter_locationdata_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Eventdata',
            new_name='Eventdatapaper',
        ),
    ]
