# Generated by Django 5.0.4 on 2024-05-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_Application', '0011_rename_eventdata_eventdatapaper'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventdataproject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=25)),
                ('Roll_no', models.CharField(default='', max_length=50)),
                ('Email', models.CharField(default='', max_length=50)),
                ('Event_name', models.CharField(default='', max_length=255)),
                ('Event_cordinator', models.CharField(default='', max_length=100)),
                ('Event_date', models.DateField(default='')),
            ],
        ),
    ]
