# Generated by Django 5.0.4 on 2024-12-28 04:16

import My_Application.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_Application', '0013_eventdatatechnical'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationdata',
            name='District',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='locationdata',
            name='Place',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='locationdata',
            name='Image',
            field=models.FileField(blank=True, null=True, upload_to=My_Application.models.filepath),
        ),
    ]
