# Generated by Django 5.0.4 on 2024-12-30 12:48

import My_Application.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_Application', '0014_locationdata_district_locationdata_place_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='finalpaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=25)),
                ('Roll_no', models.CharField(default='', max_length=50)),
                ('Email', models.CharField(default='', max_length=50)),
                ('Event_name', models.CharField(default='', max_length=255)),
                ('Event_cordinator', models.CharField(default='', max_length=100)),
                ('Event_date', models.DateField(default='')),
                ('Latitude', models.FloatField(default=0, null=True)),
                ('Longitude', models.FloatField(default=0, null=True)),
                ('Time', models.CharField(default='', max_length=20, null=True)),
                ('Date', models.DateField(auto_now_add=True, null=True)),
                ('Place', models.CharField(default='', max_length=30, null=True)),
                ('District', models.CharField(default='', max_length=30, null=True)),
                ('Image', models.FileField(blank=True, null=True, upload_to=My_Application.models.filepath)),
            ],
        ),
    ]
