# Generated by Django 5.0.4 on 2025-01-03 15:21

import My_Application.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_Application', '0015_finalpaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdatapaper',
            name='Date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='eventdatapaper',
            name='District',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='eventdatapaper',
            name='Image',
            field=models.FileField(blank=True, null=True, upload_to=My_Application.models.filepath),
        ),
        migrations.AddField(
            model_name='eventdatapaper',
            name='Latitude',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='eventdatapaper',
            name='Longitude',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='eventdatapaper',
            name='Place',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='eventdatapaper',
            name='Time',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='finalpaper',
            name='Event_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
