# Generated by Django 5.0.4 on 2025-01-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_Application', '0016_eventdatapaper_date_eventdatapaper_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdatapaper',
            name='Date',
            field=models.DateField(default='', null=True),
        ),
    ]
