# Generated by Django 5.0.4 on 2025-01-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_Application', '0017_alter_eventdatapaper_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdatapaper',
            name='Date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventdatapaper',
            name='Event_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
