# Generated by Django 5.0.4 on 2025-01-03 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_Application', '0018_alter_eventdatapaper_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='finalpaper',
        ),
        migrations.DeleteModel(
            name='LocationData',
        ),
    ]
